name: Update packages

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - master
  schedule:
    - cron: 0 00 * * *
  watch:
    types: started

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    name: Update ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: [packages,packages-19.07]
        
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install git subversion git-core wget
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x ${{matrix.target}}.sh
        git clone -b ${{matrix.target}} https://github.com/wjh040107/openwrt-packages.git ${{matrix.target}}
        cd ${{matrix.target}}
        rm -Rf *
        git rm --cache *
        $GITHUB_WORKSPACE/${{matrix.target}}.sh
    - name: Upload
      env: 
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        [ -e $GITHUB_WORKSPACE/LICENSE ] && cp $GITHUB_WORKSPACE/LICENSE $GITHUB_WORKSPACE/${{matrix.target}}
        [ -e $GITHUB_WORKSPACE/README.md ] && cp $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/${{matrix.target}}
        cd $GITHUB_WORKSPACE/${{matrix.target}}
        git add .
        git commit -m "update$(TZ='Asia/Shanghai' date +@%Y%m%d)"
        git push --quiet "https://${{ secrets.TOKEN }}@github.com/wjh040107/openwrt-packages.git" HEAD:${{matrix.target}}
        
